import { useEffect, useState } from 'react'
import { submitClaim } from '../services/claimsApi'

const pct = (value = 0) => `${(Number(value) * 100).toFixed(1)}%`
const label = (prediction) => prediction === 1 ? 'PROMPT INJECTION' : 'BENIGN'
const tone = (prediction) => prediction === 1 ? 'danger' : 'safe'
const textOr = (value, fallback) => value && String(value).trim() ? value : fallback
const LOADING_STAGES = ['Uploading Evidence...', 'Analyzing Text...', 'Running OCR...', 'Analyzing Video Frames...', 'Checking Temporal Sequence...', 'Generating AI Explanation...', 'Finalizing Decision...']

function Metric({ name, value }) { return <div className="metric"><span>{name}</span><strong>{value}</strong></div> }
function Confidence({ value }) { return <div className="confidence"><div><span>Confidence</span><strong>{pct(value)}</strong></div><div className="progress"><i style={{ width: `${Math.min(100, Math.max(0, Number(value || 0) * 100))}%` }} /></div></div> }
function GuardCard({ className, title, icon, children }) { return <section className={`guard-panel ${className}`}><div className="card-title"><span className="card-icon">{icon}</span><h3>{title}</h3></div>{children}</section> }

function AnalysisResults({ result }) {
  const decision = result.cross_modal_decision || result.final_decision || {}
  const suspicious = decision.route === 'HUMAN_REVIEW'
  const image = result.image_guard
  const video = result.video_guard
  const temporal = result.temporal_analysis
  const evidence = result.security_evidence || {}
  const llm = result.llm_analysis
  const imageAuth = result.image_authenticity
  const videoAuth = result.video_authenticity
  const authenticityFlag = evidence.fraud_risk?.evidence_authenticity_flag
  return <div className="results" role="status">
    <div className={`security-summary ${suspicious ? 'summary-danger' : 'summary-safe'}`}><div><p className="eyebrow">CLAIMSHIELD SECURITY ANALYSIS</p><h2>{suspicious ? 'Security review required' : 'Security check passed'}</h2><p>Claim ID: <strong>{result.claim_id}</strong></p></div><div className="summary-badges"><span>{suspicious ? 'SUSPICIOUS' : 'SAFE'}</span><small>AI SECURITY<br /><strong>{evidence.ai_security?.prompt_injection_detected ? 'SUSPICIOUS' : 'BENIGN'}</strong></small><small>MEDIA AUTHENTICITY<br /><strong>{authenticityFlag ? 'POSSIBLE SYNTHETIC' : 'LIKELY REAL'}</strong></small><small>FINAL ROUTE<br /><strong>{suspicious ? 'HUMAN REVIEW' : 'CONTINUE'}</strong></small></div></div>
    <div className="process-flow"><span>Claim</span><b>→</b><span>Guards</span><b>→</b><span>Temporal</span><b>→</b><span>Cross-Modal</span><b>→</b><span>Groq</span><b>→</b><span>Route</span></div>
    <div className="guard-grid">
      <GuardCard className="blue" title="Text Guard" icon="▤"><p className={`classification ${result.text_guard.is_prompt_injection === true || result.text_guard.prediction === 1 ? 'danger' : 'safe'}`}>{result.text_guard.classification || (result.text_guard.prediction === 1 ? 'PROMPT_INJECTION' : 'BENIGN')}</p><Confidence value={result.text_guard.confidence} /><Metric name="Detector" value={result.text_guard.detector || 'TF-IDF + Linear SVM'} /><p className="evidence-text">{textOr(result.text_guard.evidence_text, 'Claim narrative available')}</p><p className="muted">Prompt Injection Detected: <strong>{result.text_guard.is_prompt_injection === true || result.text_guard.prediction === 1 ? 'YES' : 'NO'}</strong></p></GuardCard>
      <GuardCard className="green" title="Image Guard" icon="▧">{image ? <><p className={`classification ${tone(image.prediction)}`}>{label(image.prediction)}</p><Confidence value={image.confidence} /><p className="field-label">OCR extracted text</p><p className="ocr-box">{textOr(image.ocr_text, 'No readable text detected')}</p><p className="muted">{image.ocr_error ? `OCR error: ${image.ocr_error}` : 'OCR completed successfully'}</p></> : <div className="not-provided">Image Evidence<br /><strong>Not Provided</strong></div>}</GuardCard>
      <GuardCard className="orange" title="Video Guard" icon="▶">{video ? <><div className="metric-row"><Metric name="Frames analyzed" value={video.frames_analyzed ?? video.analyzed_frames ?? 0} /><Metric name="Suspicious frames" value={video.suspicious_frames ?? 0} /></div>{video.error && <p className="error-text">{video.error}</p>}<div className="frame-list">{(video.frame_results || []).map((frame) => <div key={frame.timestamp}><span>{Number(frame.timestamp).toFixed(1)}s</span><span>{textOr(frame.ocr_text, 'No text')}</span><b className={frame.prediction === 1 ? 'danger-text' : 'safe-text'}>{frame.prediction === 1 ? 'Suspicious' : 'Benign'}</b><span>{pct(frame.confidence)}</span></div>)}</div></> : <div className="not-provided">Video Evidence<br /><strong>Not Provided</strong></div>}</GuardCard>
      <GuardCard className="amber" title="Temporal Analysis" icon="◷">{temporal ? <><p className={`classification ${tone(temporal.prediction)}`}>{temporal.classification || label(temporal.prediction)}</p><Confidence value={temporal.confidence} /><p className="field-label">Combined OCR sequence</p><p className="temporal-sequence">{textOr(temporal.combined_text, 'No readable text detected')}</p><p className="muted">Temporal attack detected: {temporal.is_temporal_attack ? 'Yes' : 'No'}</p></> : <div className="not-provided">Temporal Analysis<br /><strong>Not Provided</strong></div>}</GuardCard>
    </div>
    <GuardCard className="purple wide" title="Cross-Modal Security" icon="◈"><div className="signal-row"><span>Text <b>{evidence.text_signal?.malicious ? 'SUSPICIOUS' : 'BENIGN'}</b></span><span>Image <b>{evidence.image_signal?.available ? (evidence.image_signal.malicious ? 'SUSPICIOUS' : 'BENIGN') : 'NOT PROVIDED'}</b></span><span>Video <b>{evidence.video_signal?.available ? 'AVAILABLE' : 'NOT PROVIDED'}</b></span><span>Temporal <b>{evidence.temporal_signal?.malicious ? 'SUSPICIOUS' : evidence.temporal_signal?.available ? 'BENIGN' : 'NOT PROVIDED'}</b></span></div><p className="muted">Triggered guards: {evidence.triggered_guards?.join(', ') || 'None'}</p><p>Deterministic security flag: <strong>{evidence.security_flag ? 'TRUE' : 'FALSE'}</strong></p><p>Deterministic route: <strong>{evidence.deterministic_route || decision.route}</strong></p><small>Final routing is determined by ClaimShield guardrails.</small></GuardCard>
    <GuardCard className="rose wide" title="Media Authenticity Guard" icon="⌁"><p className="muted">AI-generated / manipulated evidence analysis</p><div className="auth-grid"><div><h4>Image Authenticity</h4>{imageAuth ? <><p><strong>{imageAuth.classification}</strong></p><p>Synthetic probability: {pct(imageAuth.synthetic_probability)}</p><p className="muted">{imageAuth.explanation}</p></> : <p className="muted">Not Provided</p>}</div><div><h4>Video Authenticity</h4>{videoAuth ? <><p><strong>{videoAuth.classification}</strong></p><p>Frames checked: {videoAuth.frames_checked} · Suspicious: {videoAuth.suspicious_frames}</p><p>Synthetic probability: {pct(videoAuth.synthetic_probability)}</p></> : <p className="muted">Not Provided</p>}</div></div>{authenticityFlag && <div className="auth-warning">⚠ POSSIBLE SYNTHETIC OR MANIPULATED EVIDENCE<br /><small>Human verification is required.</small></div>}</GuardCard>
    {llm && <section className="llm-panel"><div className="card-title"><span className="card-icon">✦</span><div><h3>AI Investigator Explanation</h3><p>Generated by Groq from structured ClaimShield guard outputs.</p></div><span className="role-badge">EXPLANATION ONLY</span></div>{llm.status === 'unavailable' ? <p className="llm-warning">AI explanation unavailable. Deterministic ClaimShield guards remain active.</p> : <div className="llm-grid">{[['Overall Security Summary', 'overall_security_summary'], ['Text Analysis', 'text_analysis'], ['Image Analysis', 'image_analysis'], ['Video Analysis', 'video_analysis'], ['Temporal Analysis', 'temporal_analysis'], ['Cross-Modal Analysis', 'cross_modal_analysis'], ['Investigator Explanation', 'investigator_explanation'], ['Route Explanation', 'route_explanation']].map(([title, field]) => <div key={field}><h4>{title}</h4><p>{textOr(llm[field], 'No analysis provided.')}</p></div>)}<div><h4>Why Flagged</h4><ul>{(llm.why_flagged || []).map((item, index) => <li key={index}>{item}</li>)}</ul></div></div>}<small className="llm-note">The LLM cannot override ClaimShield’s deterministic routing decision.</small></section>}
    <div className={`final-panel ${suspicious ? 'final-danger' : 'final-safe'}`}><strong>{suspicious ? '⚠ SECURITY REVIEW REQUIRED' : '✓ CLAIMSHIELD SECURITY CHECK PASSED'}</strong><span>Route: {suspicious ? 'HUMAN REVIEW' : 'CONTINUE'}</span><p>{suspicious ? 'One or more ClaimShield guardrails detected possible AI manipulation.' : 'No prompt-injection signal was detected by the available guardrails.'}</p></div>
  </div>
}

function ClaimSubmission() {
  const [form, setForm] = useState({ userId: '', claimId: '', description: '', amount: '', image: null, video: null }); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false); const [loadingStage, setLoadingStage] = useState(0)
  useEffect(() => { if (!submitting) return undefined; const timer = setInterval(() => setLoadingStage((stage) => Math.min(stage + 1, LOADING_STAGES.length - 1)), 1200); return () => clearInterval(timer) }, [submitting])
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value }); const updateFile = (event) => setForm({ ...form, [event.target.name]: event.target.files[0] || null })
  async function handleSubmit(event) { event.preventDefault(); setError(''); setResult(null); if (!form.image && !form.video) { setError('Please upload at least one evidence file: image or video.'); return } const data = new FormData(); data.append('user_id', form.userId); data.append('claim_id', form.claimId); data.append('claim_description', form.description); data.append('claim_amount', form.amount); if (form.image) data.append('image', form.image); if (form.video) data.append('video', form.video); try { setSubmitting(true); setResult(await submitClaim(data)) } catch (requestError) { setError(requestError.response?.data?.detail || requestError.message || 'Unable to submit claim. Please try again.') } finally { setSubmitting(false) } }
  return <section className="submission-card"><div className="section-heading"><p className="eyebrow">STEP 3 / CLAIM SUBMISSION</p><h2>Submit a claim for analysis</h2><p>Provide claim details and supporting evidence to begin the security review.</p></div><form onSubmit={handleSubmit}><div className="form-grid"><label>Claim ID<input name="claimId" value={form.claimId} onChange={update} required placeholder="e.g. CLM-2026-001" /></label><label>Claim Amount<input name="amount" type="number" min="0.01" step="0.01" value={form.amount} onChange={update} required placeholder="0.00" /></label></div><label>Claim Description<textarea name="description" value={form.description} onChange={update} required rows="5" placeholder="Describe the incident and circumstances of the claim" /></label><p className="evidence-help">Upload at least one type of evidence: image or video. You may upload both.</p><div className="form-grid"><label>Upload Image Evidence<input name="image" type="file" accept="image/*" onChange={updateFile} /><span className="file-name">{form.image?.name || 'No image selected'}</span></label><label>Upload Video Evidence<input name="video" type="file" accept="video/*" onChange={updateFile} /><span className="file-name">{form.video?.name || 'No video selected'}</span></label></div><button type="submit" disabled={submitting}>{submitting ? `◌ ${LOADING_STAGES[loadingStage]}` : 'ANALYZE CLAIM'}</button></form>{result && <><p className="success" role="status">Claim submitted successfully · {result.claim_id}</p><AnalysisResults result={result} /></>}{error && <p className="error" role="alert">{error}</p>}</section>
}
export default ClaimSubmission
